apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-sso
spec:
  refreshInterval: 1h
  target:
    name: immich-sso
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        #issuerUrl: "https://login.{{ $.Values.domain }}"
        immich-config.yaml: |
          oauth:
            enabled: true
            autoLaunch: true
            issuerUrl: "{{ `{{ .issuer_url }}` }}"
            clientId: "{{ `{{ .client_id }}` }}"
            clientSecret: "{{ `{{ .secret }}` }}"
            #mobileOverrideEnabled:
            #mobileRedirectUri: ""
          passwordLogin:
            enabled: false
    # TODO: Test this and probably move into a secret to handle the domain.
    #EMAIL_HOST: "smtp-relay-mail"
    #EMAIL_FROM: "pics@{{ .Values.domain }}"

  data:
    - secretKey: client_id
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "immich-sso-secret" }}'
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "immich-sso-secret" }}'
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: issuer_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "immich-sso-secret" }}'
        property: issuer
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
