---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: "pg-{{ .Release.Name }}"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6-26
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: local-path

  monitoring:
    enablePodMonitor: true

  postgresql:
    parameters:
      max_connections: "600"
      shared_buffers: 512MB

  bootstrap:
    initdb:
      database: rallly
      owner: rallly
      secret:
        name: "{{ .Release.Name }}-db"
