apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-db"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: SecretStore
  target:
    name: "{{ .Release.Name }}-db"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ index .Values "bitwardenIds" "rallly-db" }}
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: {{ index .Values "bitwardenIds" "rallly-db" }}
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
