bitwardenIds:
  cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
  argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625

assistant:
  bitwardenIds:
    home-assistant-pg: f59add53-a8fb-42cd-b784-b3c8011081df
scifi-farm:
  hugo:
    domain: scifi.farm
    title: SciFi.Farm - Aeroponic Farming & Automation
    theme: github.com/onweru/compose
    imports:
      - path: github.com/lkhrs/hugo-dark-visitors
      - path: github.com/mfg92/hugo-shortcode-gallery
      - path: github.com/OwnYourIO/SpencersLab/sites/grow
      - path: github.com/onweru/compose

base:
  bitwardenIds:
    argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625
    cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
seaweedfs-csi-driver:
  seaweedfsFiler: "seaweedfs-filer.infra.spencerslab.com:8880,seaweedfs-filer.infra.spencerslab.com:8881,seaweedfs-filer.infra.spencerslab.com:8882,seaweedfs-filer.infra.spencerslab.com:8883,seaweedfs-filer.infra.spencerslab.com:8884"
