{{ if (index .Values "bitwardenIds") }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  target:
    name: "loki-s3-secret"
    creationPolicy: Owner
  data:
    - secretKey: access_key_id
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: {{ index .Values "bitwardenIds" "loki-s3" }}
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret_access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: {{ index .Values "bitwardenIds" "loki-s3" }}
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
...
{{ end }}
---
