apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-secret
spec:
  refreshInterval: 1h
  target:
    name: smtp-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RELAYHOST: "{{ `{{ .RELAYHOST }}` }}"
        RELAYHOST_USERNAME: "{{ `{{ .RELAYHOST_USERNAME }}` }}"
        RELAYHOST_PASSWORD: "{{ `{{ .RELAYHOST_PASSWORD }}` }}"
        ALLOWED_SENDER_DOMAINS: "{{ $.Values.domain }}"
        SMTP_SECURE: "false"
  data:
    - secretKey: RELAYHOST_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "smtp-secret" }}'
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: RELAYHOST_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "smtp-secret" }}'
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: RELAYHOST
      sourceRef:
        storeRef:
          name: bitwarden-uri
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "smtp-secret" }}'
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None