apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-db"
spec:
  refreshInterval: 1h
  target:
    name: "{{ .Release.Name }}-db"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # MariaDB configuration
        MARIADB_USER: "{{ `{{ .db_username }}` }}"
        MARIADB_PASSWORD: "{{ `{{ .db_password }}` }}"
  data:
    - secretKey: db_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "playsms-db" }}'
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: db_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "playsms-db" }}'
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
