apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # PlaySMS admin password
        WEB_ADMIN_PASSWORD: "{{ `{{ .admin_password }}` }}"
        # We can do this since there in the same pod. If that changes this will too.
        MYSQL_HOST: "127.0.0.1"
        MYSQL_USER: "{{ `{{ .db_username }}` }}"
        MYSQL_PASS: "{{ `{{ .db_password }}` }}"
        MYSQL_NAME: "playsms"
  data:
    - secretKey: admin_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "playsms" }}'
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: db_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "playsms-db" }}'
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: db_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "playsms-db" }}'
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
