apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # PlaySMS admin password
        WEB_ADMIN_PASSWORD: "{{ `{{ .admin_password }}` }}"
  data:
    - secretKey: admin_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "playsms" }}'
        property: admin_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
