apiVersion: v2
name: postiz
version: 1.0.32
appVersion: 1.0.0
dependencies:
- name: app-template
  version: 4.2.0
  repository: https://bjw-s-labs.github.io/helm-charts/
- name: temporal
  version: 0.73.1
  repository: https://go.temporal.io/helm-charts
