apiVersion: v2
name: postiz
version: 1.0.45
appVersion: 1.0.0
dependencies:
- name: app-template
  version: 4.2.0
  repository: https://bjw-s-labs.github.io/helm-charts/
- name: temporal
  version: 1.0.0-rc.2
  repository: https://go.temporal.io/helm-charts
