bitwardenIds:
  postiz-pg: OVERRIDE_VIA_CUSTOM_VALUES

domain: OVERRIDE_VIA_APPSET

app-template:
  global:
    nameOverride: &chartName postiz

  controllers:
    postiz:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        main:
          image:
            repository: ghcr.io/gitroomhq/postiz-app
            tag: v2.11.3
          env:
            TZ: Etc/UTC
            IS_GENERAL: "true"
            STORAGE_PROVIDER: local
            BACKEND_INTERNAL_URL:  http://localhost:3000
            UPLOAD_DIRECTORY: /uploads
            NEXT_PUBLIC_POSTIZ_UPLOAD_DIRECTORY: /uploads
            REDIS_URL: redis://localhost:6379

          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}-secret"
            
          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 4Gi
          #securityContext:
          #  allowPrivilegeEscalation: false
          #  capabilities:
          #    drop:
          #      - ALL
        
        redis:
          image:
            repository: redis
            tag: 8.2.0
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              memory: 512Mi
      #pod:
      #  securityContext:
      #    runAsUser: 100
      #    fsGroup: 100
      #    fsGroupChangePolicy: OnRootMismatch
      #    runAsNonRoot: true

  service:
    postiz:
      controller: *chartName
      ports:
        http:
          port: 5000

  persistence:
    config:
      existingClaim: "{{ .Release.Name }}"
      globalMounts:
        - path: /config
          subPath: config
        - path: /uploads
          subPath: uploads

    nginx-logs:
      type: emptyDir
      globalMounts:
        - path: /var/lib/nginx/logs
    nginx-tmp:
      type: emptyDir
      globalMounts:
        - path: /var/lib/nginx/tmp
