bitwardenIds:
  argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625
  cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e

  admin-account: f7b628ec-2544-4c28-a476-b1a501487d99
  wekan-sso-secret: 68ce2bae-c00f-4293-8325-b23000060637
  karakeep-secret: bc65b74a-1eaf-4e57-97d0-b2ce00407cf9
  karakeep-sso: 814bba20-e097-46a9-bf6b-b33c001f5d40
  paperless-pg: 9d812113-dd8b-4343-bef1-b265001073c2
  paperless-sso-secret: 3f65d829-5e7e-44b8-b60f-b26901348eb4
  paperless-samba-secret: 6a63c15e-c02b-424d-bae0-b27e00049e09
  zigbee2mqtt: 0164cfbc-dd85-43af-a4cc-b13f00108bde


seaweedfs-csi-driver:
  seaweedfsFiler: "seaweedfs-filer.infra.spencerslab.com:8880,seaweedfs-filer.infra.spencerslab.com:8881,seaweedfs-filer.infra.spencerslab.com:8882,seaweedfs-filer.infra.spencerslab.com:8883,seaweedfs-filer.infra.spencerslab.com:8884"

zigbee2mqtt:
  bitwardenIds:
    zigbee2mqtt: 0164cfbc-dd85-43af-a4cc-b13f00108bde
zigbee2mqtt-coord:
  bitwardenIds:
    zigbee2mqtt: 0164cfbc-dd85-43af-a4cc-b13f00108bde
zigbee2mqtt-remote:
  bitwardenIds:
    zigbee2mqtt: 0164cfbc-dd85-43af-a4cc-b13f00108bde

realm: SpencersLab

wekan:
  root_url: https://wekan.spencerslab.com
boards:
  root_url: https://boards.spencerslab.com

firefly-import:
  fireflyiii:
    vanityUrl: https://firefly.spencerslab.com

# For actualbudget
trustedIPs:
  - "10.42.0.0/24"
  - "10.0.77.0/24"
