scifi-farm:
  hugo:
    domain: scifi.farm
    title: SciFi.Farm - Aeroponic Farming & Automation
    theme: github.com/onweru/compose
    imports:
      - path: github.com/lkhrs/hugo-dark-visitors
      - path: github.com/OwnYourIO/SpencersLab/sites/grow
      - path: github.com/onweru/compose
      - path: github.com/mfg92/hugo-shortcode-gallery

bitwardenIds:
  argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625
  cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e

  admin-account: f7b628ec-2544-4c28-a476-b1a501487d99
  wekan-sso-secret: 68ce2bae-c00f-4293-8325-b23000060637
  karakeep-secret: bc65b74a-1eaf-4e57-97d0-b2ce00407cf9
  karakeep-sso: 814bba20-e097-46a9-bf6b-b33c001f5d40
  paperless-pg: 9d812113-dd8b-4343-bef1-b265001073c2
  paperless-sso-secret: 3f65d829-5e7e-44b8-b60f-b26901348eb4
  paperless-samba-secret: 6a63c15e-c02b-424d-bae0-b27e00049e09
  zigbee2mqtt: 0164cfbc-dd85-43af-a4cc-b13f00108bde
  immich-sso-secret: f4dfae88-f77d-4c31-b58e-b26b0049b6f5
  immich-pg: e908eec9-232c-4aef-8665-b26a000c7469

seaweedfs-csi-driver:
  seaweedfsFiler: "seaweedfs-filer.infra.spencerslab.com:8880,seaweedfs-filer.infra.spencerslab.com:8881,seaweedfs-filer.infra.spencerslab.com:8882,seaweedfs-filer.infra.spencerslab.com:8883,seaweedfs-filer.infra.spencerslab.com:8884"

immich:
  bitwardenIds:
    immich-sso-secret: f4dfae88-f77d-4c31-b58e-b26b0049b6f5
    immich-pg: e908eec9-232c-4aef-8665-b26a000c7469

smtp-relay:
  bitwardenIds:
    smtp-secret: 876515bc-b0d6-43df-b9fa-b0dd000a601e
postiz:
  bitwardenIds:
    postiz: 51ef165e-88ab-4271-9170-b3c4011c0a70
    postiz-db: a3bf7d42-1ae7-4e8f-9d30-b3c20161ee38
    postiz-sso: 5162b942-9d85-4dcb-928b-b3c4010d3851
    temporal-db: 8c1f6224-5157-45f2-b918-b3e20133690d
    temporal-sso: 102b8418-3ddf-4564-85cf-b3e201316a60

playsms:
  bitwardenIds:
    playsms: 5d18aef1-370c-400f-850f-b3c3000648e2
    playsms-db: a99b5d7a-29cc-4216-b590-b3c300066716

rallly:
  bitwardenIds:
    rallly: 74d9f8bc-d640-488c-be79-b3c5010a6e04
    rallly-db: 7eae5e8c-90f1-47b4-ae0f-b3c4010eec7e
    rallly-sso: a48b08fa-b8ff-4a24-91a1-b3c4010e760f

zigbee2mqtt:
  bitwardenIds:
    zigbee2mqtt: 0164cfbc-dd85-43af-a4cc-b13f00108bde
zigbee2mqtt-coord:
  bitwardenIds:
    zigbee2mqtt: 0164cfbc-dd85-43af-a4cc-b13f00108bde
zigbee2mqtt-remote:
  bitwardenIds:
    zigbee2mqtt: 0164cfbc-dd85-43af-a4cc-b13f00108bde

realm: SpencersLab

wekan:
  root_url: https://wekan.spencerslab.com
boards:
  root_url: https://boards.spencerslab.com

firefly-import:
  fireflyiii:
    vanityUrl: https://firefly.spencerslab.com

# For actualbudget
trustedIPs:
  - "10.42.0.0/24"
  - "10.0.77.0/24"
