apiVersion: v2
name: traefik
version: 1.0.3
appVersion: 2.11.10
dependencies:
- name: traefik
  version: 37.1.2
  repository: https://traefik.github.io/charts
- name: crowdsec
  version: 0.20.1
  repository: https://crowdsecurity.github.io/helm-charts
