apiVersion: v2
name: traefik
version: 1.0.56
appVersion: 2.11.10
dependencies:
- name: traefik
  version: 37.4.0
  repository: https://traefik.github.io/charts
- name: crowdsec
  version: 0.22.0
  repository: https://crowdsecurity.github.io/helm-charts
