apiVersion: v2
name: traefik
version: 1.0.38
appVersion: 2.11.10
dependencies:
- name: traefik
  version: 37.4.0
  repository: https://traefik.github.io/charts
- name: crowdsec
  # Keep here until this has been addressed: https://github.com/crowdsecurity/helm-charts/issues/318
  version: 0.21.1
  repository: https://crowdsecurity.github.io/helm-charts
