---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: traefik-mqtt
  namespace: {{ $.Values.namespace }}
  labels:
    # Needed to address: https://github.com/argoproj/argo-cd/issues/4188
    app.kubernetes.io/part-of: traefik
spec:
  refreshInterval: 1h
  target:
    name: traefik-mqtt
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MQTT_USERNAME: "{{ `{{ .username }}` }}"
        MQTT_PASSWORD: "{{ `{{ .password }}` }}"
        MQTT_URI: "mqtt.{{ .Values.domain }}:1883"
        MQTT_TOPIC: "keycloak"
        ALLOWLIST_FILE: /tmp/allowlist.yaml
        SMTP_SERVER: smtp-relay-mail
        FROM_EMAIL: "login@{{ .Values.domain }}"
        ADMIN_EMAILS: "admin@{{ .Values.domain }}"
  data:
  - secretKey: username
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: SecretStore
    remoteRef:
      key: {{ index .Values "bitwardenIds" "traefik-mqtt" }}
      property: username
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: password
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: SecretStore
    remoteRef:
      key: {{ index .Values "bitwardenIds" "traefik-mqtt" }}
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
...
