apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-keys
  namespace: {{ $.Values.namespace }}
  labels:
    # Needed to address: https://github.com/argoproj/argo-cd/issues/4188
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  target:
    name: crowdsec-keys
    creationPolicy: Owner
  data:
  - secretKey: ENROLL_KEY
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: SecretStore
    remoteRef:
      key: {{ index .Values "bitwardenIds" "crowdsec-secret" }}
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      property: username
  - secretKey: csLapiSecretKey
    sourceRef:
      storeRef:
        name: bitwarden-login
        kind: SecretStore
    remoteRef:
      key: {{ index .Values "bitwardenIds" "crowdsec-secret" }}
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      property: password
  - secretKey: registrationToken
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: SecretStore
    remoteRef:
      key: {{ index .Values "bitwardenIds" "crowdsec-secret" }}
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      property: token

