apiVersion: v2
name: base
version: 1.0.178
appVersion: 1.0.31
dependencies:
- name: argo-cd
  version: 8.6.4
  repository: https://argoproj.github.io/argo-helm
- name: cert-manager
  version: v1.19.0
  repository: https://charts.jetstack.io
