bitwardenIds:
  cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
  argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625

base:
  bitwardenIds:
    argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625
    cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
smtp-relay:
  bitwardenIds:
    smtp-secret: 876515bc-b0d6-43df-b9fa-b0dd000a601e

seaweedfs-csi-driver:
  seaweedfsFiler: "seaweedfs-filer.infra.spencerslab.com:8880,seaweedfs-filer.infra.spencerslab.com:8881,seaweedfs-filer.infra.spencerslab.com:8882,seaweedfs-filer.infra.spencerslab.com:8883,seaweedfs-filer.infra.spencerslab.com:8884"
  volume-count: 5