bitwardenIds:
  keycloak: f7b628ec-2544-4c28-a476-b1a501487d99
  keycloak-pg: 77443679-1d79-49a2-840f-b25c01334c21
  smtp: 876515bc-b0d6-43df-b9fa-b0dd000a601e
  gitea: 2ca2457b-dc62-413a-af99-b1f8017ef7cd
  gitea-admin: f7b628ec-2544-4c28-a476-b1a501487d99
  argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625
  cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e

base:
  bitwardenIds:
    cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
    argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625
smtp-relay:
  bitwardenIds:
    smtp-secret: 876515bc-b0d6-43df-b9fa-b0dd000a601e

389ds:
  bitwardenIds:
    389ds: f7b628ec-2544-4c28-a476-b1a501487d99

keycloakx:
  bitwardenIds:
    keycloak: f7b628ec-2544-4c28-a476-b1a501487d99
    keycloak-pg: 77443679-1d79-49a2-840f-b25c01334c21

trustedIPs:
  - "10.42.0.0/24"
  - "10.0.77.0/24"
