apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: SecretStore
  target:
    name: keycloak-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        KC_SPI_EVENTS_LISTENER_MQTT_SERVER_URI: "tcp://mqtt.{{ .Values.domain }}:1883"
        KC_SPI_EVENTS_LISTENER_MQTT_USERNAME: "{{ `{{ MQTT_USERNAME }}` }}"
        KC_SPI_EVENTS_LISTENER_MQTT_PASSWORD: "{{ `{{ MQTT_PASSWORD }}` }}"
        KC_SPI_EVENTS_LISTENER_MQTT_PUBLISHER_ID: kc-mqtt
        KC_SPI_EVENTS_LISTENER_MQTT_TOPIC: keycloak
        KC_SPI_EVENTS_LISTENER_MQTT_USE_PERSISTENCE: true
        KC_SPI_EVENTS_LISTENER_MQTT_RETAINED: true
        KC_SPI_EVENTS_LISTENER_MQTT_CLEAN_SESSION: true
        KC_SPI_EVENTS_LISTENER_MQTT_QOS: 0
  data:
  - secretKey: KEYCLOAK_ADMIN
    remoteRef:
      key: {{ index .Values "bitwardenIds" "keycloak" }}
      property: username
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: KEYCLOAK_ADMIN_PASSWORD
    remoteRef:
      key: {{ index .Values "bitwardenIds" "keycloak" }}
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: MQTT_USERNAME
    remoteRef:
      key: {{ index .Values "bitwardenIds" "keycloak-mqtt" }}
      property: username
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: MQTT_PASSWORD
    remoteRef:
      key: {{ index .Values "bitwardenIds" "keycloak-mqtt" }}
      property: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

