apiVersion: v2
name: traefik
version: 1.0.6
appVersion: 2.11.10
dependencies:
- name: traefik
  version: 37.4.0
  repository: https://traefik.github.io/charts
# Maybe this actually isn't used for proxy-remote
#- name: crowdsec
#  # Keep here until this has been addressed: https://github.com/crowdsecurity/helm-charts/issues/318
#  version: 0.20.1
#  repository: https://crowdsecurity.github.io/helm-charts
