bitwardenIds:
  cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
  argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625

base:
  bitwardenIds:
    cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
    argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625

loki: 
  bitwardenIds:
    loki-s3: 06a65037-29d3-48de-978c-b3b6002d3978

exporter-mikrotik:
  bitwardenIds:
    exporter-mikrotik: 87082494-47f1-4efc-926e-b1df016b9428
