apiVersion: v2
name: seaweedfs-csi-driver
version: 1.0.2
appVersion: 1.0.0
dependencies:
- name: seaweedfs-csi-driver
  version: 0.2.9
  repository: https://seaweedfs.github.io/seaweedfs-csi-driver/helm
