bitwardenIds:
  cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
  argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625

# Coder and open-webui secrets are currently in the gpu service, so keep at that level.
#coder:
#  bitwardenIds:
  coder-sso-secret: 6052ca6f-bf5d-47bb-8194-b33e000a9455
  coder-pg: e197f717-0cd6-4634-8388-b33e000ae174
#open-webui:
#  bitwardenIds:
  open-webui-sso-secret: 69e653a3-061c-4727-af4b-b336014cedbe
  open-webui-secret: b56bd559-e590-42eb-a98a-b336014dc3e7
  open-webui-pg: 3d3e5fa0-d0f0-4a95-a9e1-b336014f13f8
base:
  bitwardenIds:
    argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625
    cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
hivetools:
  bitwardenIds:
    github-mcp: f4938da9-3260-42c7-9787-b38100023fc3

langgraph:
  bitwardenIds:
    langgraph: 43901b8d-ba0f-4f56-89a3-b37700d75a70
    langgraph-pg: ad6b3cdf-ef6f-4ff5-bbe3-b37700d86194

n8n:
  bitwardenIds:
    n8n: 94cc6ec2-5c62-407b-a04a-b34a0166d615
flowise:
  bitwardenIds:
    flowise-pg: 7533ab94-6308-4afa-a6fe-b34a00395edd
langflow:
  bitwardenIds:
    langflow-pg: c2f26e5d-84fc-404d-93b7-b34a0157b6a0
    langflow: f7b628ec-2544-4c28-a476-b1a501487d99
supabase:
  bitwardenIds:
    supabase: ce98dd73-28ff-48e3-849d-b36c00fd09ac
    supabase-pg: 41d3450d-b750-4ae4-9cb0-b35700ff079b
    # Not needed as sso seem to be configured via UI.
    #supabase-sso: OVERRIDE_NEEDED
archon:
  bitwardenIds:
    archon: 61978548-a135-449f-8351-b36c01098d74
    # This might be more like supabase?
    archon-pg: 22c77ff4-750f-4c94-ba1d-b36c0109e75c
    # No sso for Archon yet.
    #archon-sso: OVERRIDE_NEEDED

seaweedfs-csi-driver:
  seaweedfsFiler: "seaweedfs-filer.infra.spencerslab.com:8880,seaweedfs-filer.infra.spencerslab.com:8881,seaweedfs-filer.infra.spencerslab.com:8882,seaweedfs-filer.infra.spencerslab.com:8883,seaweedfs-filer.infra.spencerslab.com:8884"

