bitwardenIds:
  home-assistant-pg: OVERRIDE_VIA_CLUSTER_ANNOTATION

domain: OVERRIDE_VIA_APPSET
clusterName: OVERRIDE_VIA_APPSET

charts:
  # Internal charts (no version/repository - uses charts/ directory)
  scifi-farm:
    #version: 1.0.10 # renovate: datasource=helm registryUrl=https://ownyourio.github.io/SpencersLab/
    #repository: https://ownyourio.github.io/SpencersLab/
    namespace: default
    ServerSideApply: "true"
    chart: hugo
  assistant:
    #version: 1.0.10 # renovate: datasource=helm registryUrl=https://ownyourio.github.io/SpencersLab/
    #repository: https://ownyourio.github.io/SpencersLab/
    namespace: default
    ServerSideApply: "true"
    chart: home-assistant
  k8s-monitoring:
    #version: 1.0.10 # renovate: datasource=helm registryUrl=https://ownyourio.github.io/SpencersLab/
    #repository: https://ownyourio.github.io/SpencersLab/
    namespace: default
    ServerSideApply: "true"
  external-secrets-bitwarden:
    version: 1.0.10 # renovate: datasource=helm registryUrl=https://ownyourio.github.io/SpencersLab/
    repository: https://ownyourio.github.io/SpencersLab/
    namespace: default
    ServerSideApply: "true"

  # External charts (with version and repository)
  cloudnative-pg:
    version: 0.25.0
    repository: https://cloudnative-pg.github.io/charts
    namespace: default
    ServerSideApply: "true"

ingress:
  dashboardProvider: homepage # Set to "homepage" to enable Homepage annotations on ingress objects
  subdomains:
    cluster:
      clusterBase: true
      service: argocd-server
      port: 80
    traefik:
      clusterBase: true
      namespace: kube-system
      service: traefik
      port: 8080
