bitwardenIds:
  autossh-secret: 449d6ac2-847d-4b2b-b0f2-b21d00003fc1
  cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
  argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625

base:
  bitwardenIds:
    cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
    argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625

sshd:
  controllers:
    main:
      containers:
        main:
          env:
            #TZ: America/Denver
            PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAy1rO5LsbzIrtqXCN6aJeLrJRlJIREC7nJZOUqsDaie"

proxy:
  subdomains:
    shows-4k:
      enabled: false
    movies-4k:
      enabled: false
