# TODO: Disabled until Home Assistant pod is added.
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: "{{ .Release.Name }}"
#  namespace: default
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 5Gi
