apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "pg-{{ .Release.Name }}-secret"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-login
    kind: SecretStore
  target:
    name: "pg-{{ .Release.Name }}-secret"
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "home-assistant-pg" }}'
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "home-assistant-pg" }}'
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
