apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}"
spec:
  refreshInterval: 1h
  target:
    name: "{{ .Release.Name }}"
    creationPolicy: Owner
  data:
    - secretKey: pg_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "home-assistant-pg" }}'
        property: username
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: pg_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "home-assistant-pg" }}'
        property: password
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    #- secretKey: admin_username
    #  sourceRef:
    #    storeRef:
    #      name: bitwarden-login
    #      kind: SecretStore
    #  remoteRef:
    #    key: '{{ index .Values "bitwardenIds" "home-assistant" }}'
    #    property: username
    #    # Boiler plate needed for ArgoCD to not complain about a mismatch.
    #    conversionStrategy: Default
    #    decodingStrategy: None
    #    metadataPolicy: None
    #- secretKey: admin_password
    #  sourceRef:
    #    storeRef:
    #      name: bitwarden-login
    #      kind: SecretStore
    #  remoteRef:
    #    key: '{{ index .Values "bitwardenIds" "home-assistant" }}'
    #    property: password
    #    # Boiler plate needed for ArgoCD to not complain about a mismatch.
    #    conversionStrategy: Default
    #    decodingStrategy: None
    #    metadataPolicy: None
