---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-login
  namespace: {{ $.Values.namespace }}
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli:8087/object/item/{{ `{{ .remoteRef.key }}` }}"
      headers:
        Content-Type: application/json
      result:
        jsonPath: "$.data.login.{{ `{{ .remoteRef.property }}` }}"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-uri
  namespace: {{ $.Values.namespace }}
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli:8087/object/item/{{ `{{ .remoteRef.key }}` }}"
      result:
        jsonPath: "$.data.login.uris[0].uri"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-fields
  namespace: {{ $.Values.namespace }}
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli:8087/object/item/{{ `{{ .remoteRef.key }}` }}"
      result:
        jsonPath: "$.data.fields[?@.name==\"{{ `{{ .remoteRef.property}}` }}\"].value"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: bitwarden-notes
  namespace: {{ $.Values.namespace }}
spec:
  provider:
    webhook:
      url: "http://bitwarden-cli:8087/object/item/{{ `{{ .remoteRef.key }}` }}"
      result:
        jsonPath: "$.data.notes"
---
