apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-secret"
spec:
  refreshInterval: 1h
  target:
    name: "{{ .Release.Name }}-secret"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ `{{ .pg_username }}` }}:{{ `{{ .pg_password }}` }}@pg-postiz-rw:5432/postiz"
        FRONTEND_URL: "https://postiz.{{ $.Values.domain }}"
        username: "{{ `{{ .pg_username }}` }}"
        password: "{{ `{{ .pg_password }}` }}"
        NEXT_PUBLIC_BACKEND_URL: "https://postiz.{{ $.Values.domain }}/api"
  data:
    - secretKey: pg_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "postiz-db" }}'
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: pg_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "postiz-db" }}'
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
