apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-secret"
spec:
  refreshInterval: 1h
  target:
    name: "{{ .Release.Name }}-secret"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ `{{ .pg_username }}` }}:{{ `{{ .pg_password }}` }}@pg-postiz-rw:5432/postiz"
        FRONTEND_URL: "https://postiz.{{ $.Values.domain }}"
        MAIN_URL: "https://postiz.{{ $.Values.domain }}"
        NEXT_PUBLIC_BACKEND_URL: "https://postiz.{{ $.Values.domain }}/api"
        # App configuration
        #JWT_SECRET:
        username: "{{ `{{ .pg_username }}` }}"
        password: "{{ `{{ .pg_password }}` }}"
        
        # For SSO
        POSTIZ_GENERIC_OAUTH: "true"

        # Display settings
        NEXT_PUBLIC_POSTIZ_OAUTH_DISPLAY_NAM: "Keycloak"
        NEXT_PUBLIC_POSTIZ_OAUTH_LOGO_URL: https://www.keycloak.org/resources/images/logo.svg"

        # Keycloak OIDC endpoints
        POSTIZ_OAUTH_URL: "{{ `{{ .provider_url }}` }}"
        POSTIZ_OAUTH_AUTH_URL: "{{ `{{ .provider_url }}` }}/protocol/openid-connect/auth"
        POSTIZ_OAUTH_TOKEN_URL: "{{ `{{ .provider_url }}` }}/protocol/openid-connect/token"
        POSTIZ_OAUTH_USERINFO_URL: "{{ `{{ .provider_url }}` }}/protocol/openid-connect/userinfo"

        # Your Keycloak client credentials
        POSTIZ_OAUTH_CLIENT_ID: "{{ `{{ .client_id }}` }}"
        POSTIZ_OAUTH_CLIENT_SECRET: "{{ `{{ .secret }}` }}"
  data:
    # For JWT
    - secretKey: pg_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "postiz" }}'
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    # For DB
    - secretKey: pg_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "postiz-db" }}'
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: pg_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "postiz-db" }}'
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    # For SSO
    - secretKey: client_id
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "postiz-sso" }}'
        property: username
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "postiz-sso" }}'
        property: password
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: provider_url
      sourceRef:
        storeRef:
          name: bitwarden-uri
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "postiz-sso" }}'
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
