apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "{{ .Release.Name }}-temporal-secret"
spec:
  refreshInterval: 1h
  target:
    name: "{{ .Release.Name }}-temporal-secret"
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        #FRONTEND_URL: "https://temporal.{{ $.Values.domain }}"

        # DB
        username: "{{ `{{ .pg_username }}` }}"
        password: "{{ `{{ .pg_password }}` }}"
        #DATABASE_URL: "postgresql://{{ `{{ .pg_username }}` }}:{{ `{{ .pg_password }}` }}@pg-temporal-rw:5432/temporal"

        # For SSO
        TEMPORAL_AUTH_ENABLED: "true"
        # Keycloak OIDC endpoints
        TEMPORAL_AUTH_PROVIDER_URL: "{{ `{{ .provider_url }}` }}"
        TEMPORAL_AUTH_CALLBACK_URL: "https://temporal.{{ $.Values.domain }}/auth/sso/callback"
        #POSTIZ_OAUTH_AUTH_URL: "{{ `{{ .provider_url }}` }}/protocol/openid-connect/auth"
        #POSTIZ_OAUTH_TOKEN_URL: "{{ `{{ .provider_url }}` }}/protocol/openid-connect/token"
        #POSTIZ_OAUTH_USERINFO_URL: "{{ `{{ .provider_url }}` }}/protocol/openid-connect/userinfo"
        # Keycloak client credentials
        TEMPORAL_AUTH_CLIENT_ID: "{{ `{{ .client_id }}` }}"
        TEMPORAL_AUTH_CLIENT_SECRET: "{{ `{{ .secret }}` }}"
        # Display settings
        #NEXT_PUBLIC_POSTIZ_OAUTH_DISPLAY_NAM: "Keycloak"
        #NEXT_PUBLIC_POSTIZ_OAUTH_LOGO_URL: https://www.keycloak.org/resources/images/logo.svg"

        # SMTP
        #EMAIL_PROVIDER: nodemailer
        #EMAIL_HOST: smtp-relay-mail.default
        #EMAIL_FROM_NAME: "Lab"
        #EMAIL_FROM_ADDRESS: "lab@{{ .Values.domain }}"

  data:
    # For DB
    - secretKey: pg_username
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "temporal-db" }}'
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: pg_password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "temporal-db" }}'
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

    # For SSO
    - secretKey: client_id
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "temporal-sso" }}'
        property: username
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "temporal-sso" }}'
        property: password
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: provider_url
      sourceRef:
        storeRef:
          name: bitwarden-uri
          kind: SecretStore
      remoteRef:
        key: '{{ index .Values "bitwardenIds" "temporal-sso" }}'
        # Boiler plate needed for ArgoCD to not complain about a mismatch.
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
