seaweedfs-csi-driver:
  seaweedfsFiler: "seaweedfs-filer-0.infra.spencerslab.com:8880,seaweedfs-filer-1.infra.spencerslab.com:8881,seaweedfs-filer-2.infra.spencerslab.com:8882,seaweedfs-filer-3.infra.spencerslab.com:8883,seaweedfs-filer-4.infra.spencerslab.com:8884"

bitwardenIds:
  autossh-secret: 449d6ac2-847d-4b2b-b0f2-b21d00003fc1
  cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
  argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625

base:
  bitwardenIds:
    cert-manager-solver-token: 0f8504eb-1339-4a32-861b-af440002801e
    argocd-sso-secret: 6bc8ead2-faf6-4548-9831-b1a501646625

smtp-relay:
  bitwardenIds:
    smtp-secret: 876515bc-b0d6-43df-b9fa-b0dd000a601e

traefik: 
  keycloak:
    realm: SpencersLab
  bitwardenIds:
    crowdsec-secret: 9e144cd6-5e85-4ded-b913-b228003c68a0
    traefik-sso-secret: fa9bb676-c5a9-431e-903f-b22b0038bf5c
  # Skip registering for now. Currently timedout.
  #crowdsec:
  #  lapi:
  #    env:
  #      - name: DISABLE_ONLINE_API
  #        value: "true"

authRealm: SpencersLab

